/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: TNB                                                   *
* Dimensions:  64 * 64                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmTNB;

#if 0


/*********************************************************************
*
*  This palette is included for reference only
*  As it is saved as device dependent bitmap without color info.
*  Please note that this bitmap requires the physical palette to be
*  identical to the palette of the display.
*  If this does not work out, please convert your bitmap into a DIB 
*/
/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _ColorsTNB[] = {
  0xFFFFFF, 0x000000
};

#endif

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalTNB = {
  2,  // Number of entries
  0,  // No transparency
  NULL
};

static GUI_CONST_STORAGE unsigned char _acTNB[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, X__XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, ______X_, _XX_____, _XXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXX__, _XX_____, X____XX_, ___XXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXX___, ____X__X, ____X___, XX__XXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXX__X_, _____X__, ________, __X___XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXX_____, __X___X_, ________, ____X__X, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XX__X___, ___X____, ________, _____X__, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X__X____, ____X___, ________, ________, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, __X_____, ______X_, __X_____, ______X_, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, _X______, ______X_, ___X____, _______X, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, _X______, ________, ___X__X_, _______X, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ________, ___XX__X, ________, ________, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, X_____X_, __XXXXX_, XX_X____, ________, X_XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, X____XXX, XXXXXXXX, XX_XXX__, ____X___, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, ____XXXX, XXXXXXXX, XXXXXXXX, _X___X__, X_XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, _X__XXXX, XXXXXXXX, XXXXXXXX, X_X___X_, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, X___XXXX, XXXXXXXX, XXXXXXXX, XX_X____, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, XX__XXXX, XXXXXXXX, XXXXXXXX, XXXXX__X, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, X__XXXXX, XXXXXXXX, XXXXXXXX, XXXXX__X, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, X__XXXXX, X_XXXXXX, XXXXXXXX, _XXXXX_X, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, X_XX____, ____XXXX, XXXX____, __XXXX__, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ________, ______XX, XX______, _____X__, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, _X__XXXX, XXXX____, X____XXX, XXX___X_, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, ____XX__, ___XXX__, __XXX___, _XXX___X, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX_X, _X__X___, ____X__X, __X_____, __X__X__, X_XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, _XX_XXXX, XXX_X__X, __XX_X_X, X_X__X__, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, XXX__XXX, XXXX___X, X__XXXXX, XXX__X__, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, XXXX____, ______XX, XX______, ____XX__, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, _XXXXX__, ____XXXX, XXX_____, ___XXX__, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, _XXXXXXX, XXXX__XX, XXXXXXXX, XXXXXX__, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, _XXXXXXX, XXX__X_X, XXX_XXXX, XXXXXX__, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, __XXXXXX, XX__XXX_, _XXX_XXX, XXXXXX__, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, __XXXXXX, XX__X__X, X__X_XXX, XXXXXX__, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, __XXXXXX, XXXX____, ____XXXX, XXXXXX__, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, X__XXXXX, XXXXX_X_, _XXXXXXX, XXXXX___, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X__XXXXX, XXXXXXXX, _XXXXXXX, XXXXX__X, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XX_XXXXX, XXXX____, ___XXXXX, XXXX_XXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XX__XXXX, XXX__XX_, _X__XXXX, XXXX__XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXX_XXXX, XX__X___, ______XX, XXXX_XXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXX__XXX, X____X_X, XXX____X, XXX__XXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXX_XXX, XXXXXXX_, _XXXXXXX, XXX_XXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXX_XX, XXXXXXX_, __XXXXXX, XX__XXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXX__X, XXXXX___, X__XXXXX, XX_XXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXX__, XXXXXXXX, XXXXXXXX, ____XXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXX_, _XXXXXXX, XXXXXXX_, _X_XXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X_____X_, ___XXXXX, XXXXX___, XXX__XXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X___X__X, _____XX_, XXX____X, X___X__X, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXX___X, __XX___X, __X_____, _____XXX, XXX_____, ___XXXXX, XXXXXXXX,
  XXXXXXX_, _X__X__X, ______XX, X__XXX__, _XXXXXXX, XXX_____, X___XXXX, XXXXXXXX,
  XXXXX___, ____XXXX, ____XXXX, XX_XXX_X, XXXXXXXX, XX_XX__X, X_____XX, XXXXXXXX,
  XXXX__XX, __XX_XXX, X__XXXXX, XXX_XX__, XXXXXXX_, __XX_X__, XX_X___X, XXXXXXXX,
  XX__XX__, _XX_XXXX, XXXXXXXX, XXXXXXX_, _XXXXXXX, _XXX_XX_, __XXXX__, XXXXXXXX,
  XX_____X, XXX__XXX, XX__XXXX, XXXXXXXX, XXXXXXX_, XXXXX___, XXXXXXX_, _XXXXXXX,
  XXX___XX, _XXX__XX, XXX__XXX, XXXXXXXX, XXXXXXXX, XXXX___X, XXXXX_XX, __X_XXXX,
  XXX____X, XXXXX__X, XXXX_XXX, XXXXXX_X, XXXXXXXX, XXXX__XX, XXXXX_XX, ____XXXX,
  X___XX__, _X___X__, XXXXXX_X, XXXXXXXX, XXXXXXXX, XXXX__XX, XXXXXXX_, X__X_XXX,
  ___XXXX_, __XXXXX_, XXXXXX__, X__XXXXX, XXXXXXXX, XXX__XXX, XXXXXX__, ___XX_XX,
  XXXXXXXX, __XXXXXX, _XXXXXX_, _X_XXXXX, XXXXXXXX, XX__XXXX, XXXXXX_X, _X__XX_X
};

GUI_CONST_STORAGE GUI_BITMAP bmTNB = {
  64, // xSize
  64, // ySize
  8, // BytesPerLine
  1, // BitsPerPixel
  _acTNB,  // Pointer to picture data (indices)
  &_PalTNB   // Pointer to palette
};

/*************************** End of file ****************************/
