/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: WYF                                                   *
* Dimensions:  64 * 64                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmWYF;

#if 0


/*********************************************************************
*
*  This palette is included for reference only
*  As it is saved as device dependent bitmap without color info.
*  Please note that this bitmap requires the physical palette to be
*  identical to the palette of the display.
*  If this does not work out, please convert your bitmap into a DIB 
*/
/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
* 1   The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _ColorsWYF[] = {
  0xFFFFFF, 0x000000
};

#endif

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalWYF = {
  2,  // Number of entries
  0,  // No transparency
  NULL
};

static GUI_CONST_STORAGE unsigned char _acWYF[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________, _____XXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, ______XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, _______X, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, _______X, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XX______, ________, ________, ________, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XX______, ________, ________, ________, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X_______, ________, ________, ________, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X_______, ________, ________, ________, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, ________, ________, ________, ________, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, ________, ___XX___, _XXX____, ________, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ________, XXXXXXXX, XXXXXXXX, XX______, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, _______X, XXXXX_XX, XXXXXXXX, XXX_____, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ______X_, XXXXXXXX, XXXXXXXX, XXXXX___, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, _____XXX, XXXXXXXX, XXXXXXXX, XX__X___, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ____XXXX, XXXXXXXX, XXXXXXXX, _XXXX___, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ____XXXX, XXXXXXXX, XXXXXXXX, XXX_X___, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ___X_XX_, ____XXXX, XXXXX___, ___XXXX_, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ___XXX__, _____XXX, XXXX____, ______X_, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, __XXX___, _______X, XX______, ________, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, ________, ________, _____XXX, XXX_X__X, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, _____XXX, X___XX__, ___X____, ___XX__X, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, ____XXX_, ________, X__X____, ____X__X, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, __X_XX_X, ________, X_______, _XX_X__X, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, __X__X__, XXX_XX__, XX__XX_X, XXXX___X, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, __X__X__, XXX_X___, XX___XXX, XXXX__XX, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, __XX__XX, XXXXX__X, XXX_____, _______X, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, __XX____, ______XX, XX_X____, ____XXXX, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, _X_XX___, ____XX_X, XX___XXX, XXXXXXXX, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, ___XXXXX, XXXXX__X, XX____XX, XXXXXXX_, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, __XXXXXX, XXX__XX_, XX_X__XX, XXXXXXX_, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X__XXXXX, XXX_X___, ______XX, XXXXXX__, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XX__XXXX, XXXXX___, X____XXX, XXXX_X__, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXX_XXXX, XXXXXXXX, XXXXXXXX, XXXXXX_X, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXX_XXXX, XXXXXXXX, XXX_XXXX, XXXXX__X, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXX__XXX, XXX_XX__, ____XXXX, XXXXX__X, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXX_XXX, XXX_X___, _____XXX, XXXXX__X, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXX__XX, XXX_____, _______X, XXXX__XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXX_XX, XXXX____, ______XX, XXXX__XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXX__X, XXXXX___, _____XXX, XXX__XXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXX_XX, XXXXXX__, ____XXXX, XXX__XXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXX__XX, XXXXXXXX, XXXXXXXX, XXX__XXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXX__XX, _XXXXXXX, XXXXXXXX, __XX__XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXX___XX, ___XXXX_, _XXXXX__, _XX___XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXX____X, XX___XXX, X_XXX___, XXX____X, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XX______, XXX_____, _______X, X_______, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, ________, _XX_____, ______XX, ________, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, ________, __XX__XX, XXXXX___, ________, _____XXX, XXXXXXXX,
  XXXXXXXX, XXXXX___, ________, ___XXX_X, XXX____X, ________, ________, XXXXXXXX,
  XXXXXXXX, XXX_____, ________, _X___XXX, X_____XX, ________, ________, __XXXXXX,
  XXXXXXXX, ________, ___X__X_, ___X____, ___X__X_, _X______, ________, _____XXX,
  XXXXXX__, ________, ________, ___X____, __X_____, ________, ________, _______X,
  XXX_____, ________, ________, _____X__, ________, ________, ________, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmWYF = {
  64, // xSize
  64, // ySize
  8, // BytesPerLine
  1, // BitsPerPixel
  _acWYF,  // Pointer to picture data (indices)
  &_PalWYF   // Pointer to palette
};

/*************************** End of file ****************************/
